version: "3.4"

services:
  docker-tripsupp-api:
    image: ${DOCKER_REGISTRY-}docker-tripsupp-api
    build:
      context: .
      dockerfile: TripSupp.WebAPI/Dockerfile
    ports:
      - "8000:80"

  docker-tripsupp-webapp:
    image: ${DOCKER_REGISTRY-}docker-tripsupp-webapp
    build:
      context: .
      dockerfile: TripSupp.WebApp/Dockerfile
    ports:
      - "4001:3000"
    depends_on:
      - docker-tripsupp-api
